### ISSUE TITLE
"window is not defined" on several entities

### ISSUE THREAD

**Issue by joshua-nicholson** [mythridium/combat-simulator#19]
**Describe the bug**
When simulating several different things, I see "Insufficient simulation time: window is not defined".

**To Reproduce**
1. Toggle all dungeons and monsters to be on.
2. Simulate all
3. Attempt to go to "Air God Dungeon" results (but note that this happens for other dungeons and monsters as well).

**Screenshots**
![image](https://github.com/mythridium/combat-simulator/assets/12222958/8502eced-81ef-4da0-a4a2-e622c6418983)
![image](https://github.com/mythridium/combat-simulator/assets/12222958/76e1b1f0-b7ba-4d1f-b0da-f24a4288cadd)

**Device:**
Tried in both Brave and Edge

**Save**
[melvor_save.txt](https://github.com/mythridium/combat-simulator/files/12864781/melvor_save.txt)

**Mod List**
SEMI Core
[Myth] Combat Simulator
SEMI Auto Farming
Show Skill Modifiers
Will I Die?
Bypass Agility Costs

**Comment by mythridium** [comment]
Thanks so much for reporting this, looks like the latest game hotfix introduced this issue in the combat simulator.

I've released a fix for this.

Fixed in 68b11228a8c28414aca8cfd5a211691b22bae6b8

**Comment by joshua-nicholson** [comment]
This appears to have fixed the "window is not defined" error, however I still see the "Insufficient simulation time" error that was present in my original screenshot. It seems like it's still able to calculate some things, but I'm specifically interested in drops/h which shows as "N/A".

Just to confirm I've updated the mod correctly, I am running version 2.2.13.

![image](https://github.com/mythridium/combat-simulator/assets/12222958/bde0bf7d-5169-4804-9b2b-4ec7d0be6332)

**Comment by mythridium** [comment]
That one is not a bug, it's saying that you are killing the monster too slow to get an accurate result.

![image](https://github.com/mythridium/combat-simulator/assets/132613374/ad98c4e1-9e2a-40e5-85cb-e674a9118990)

Try increasing the ticks and trials, to maybe 2000 each.

This will make the simulation take longer but sim for a longer duration before giving up. You might get a more accurate result that way.

**Comment by joshua-nicholson** [comment]
I got it to complete with 4000 trials and 10k max tick/trial but am still seeing N/A for drops. Anything else I'm missing?

**Comment by mythridium** [comment]
Ahh, I see there was a bug with the god dungeons not calculating the drops. I've just released a fix for this.

![image](https://github.com/mythridium/combat-simulator/assets/132613374/f9bcd210-3d3f-42c1-b303-1b137c2d4962)

You should be able to now go to the drop chance settings and filter for a specific item, and it will show the drop rate.

In this example, you could expect 1.8 aeris god boots per hour of farming while opening the chests.

Fixed in 449eecc4c4b0d1c7d85ed1bfbd42cc0c0e81a191

**Comment by joshua-nicholson** [comment]
You're awesome, thank you!
